apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rvjkhsuvt-go 
  janus-idp.io/tekton: rvjkhsuvt-go
  backstage.io/kubernetes-id: rvjkhsuvt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rvjkhsuvt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  